### ISSUE TITLE
Ready for 1.1.0 on npm

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks-vimeo-provider#10]
We're ready to update this on NPM. 

@kixxauth can you add the rest of us as collaborators?

changes:
- Breaks calls to getVideo for non-pro/business Vimeo accounts due to the API not providing stream URLs for low-tier users
- Ensures accessToken can be overridden by future channel updates to `channel.secrets`

**Comment by kixxauth** [comment]
Here is how this is done (FYI)

https://docs.npmjs.com/cli/owner

Example:

```
~$ npm owner add oddworks oddworks-ooyala-provider
+ oddworks (oddworks-ooyala-provider)
```

**Comment by kixxauth** [comment]
Reopening for brkattk to release the new version

**Comment by brkattk** [comment]
released
