### ISSUE TITLE
Handle expiring media URLs

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks-vimeo-provider#3]
A thought about expiring media URLs:

The expiration time is set by the server and does not change on subsequent requests until it is expired. This wouldn't jive well with our spec's TTL, but since the expiration time is in the media URL maybe we can parse it out and re-set the spec's expiration time based on the responses we get.

**Comment by kixxauth** [comment]
Yeah, I think that would work.

FYI, just for the record, the spec has 2 cache settings:

`maxAge` and `staleWhileRevalidate`. When the maxAge is reached, the provider will be called by oddworks in the background, and a "stale" video object will be returned to the device. When staleWhileRevalidate is reached, and the video object has not been updated, a device request will block until the provider is done doing its job.

Both settings are set in seconds.

staleWhileRevalidate should be very long. Hours long.

The maxAge can be set by the channel settings, default settings, or the provider. Sounds like we need to do it in the provider in this case.

Moar maths.

https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L116-L174

**Comment by brkattk** [comment]
Re: https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/queries/index.js#L144-L146

Where is the `object.meta.updatedAt` being set?

**Comment by kixxauth** [comment]
`object.meta.updatedAt` is set in the catalog `setItem` command:

https://github.com/oddnetworks/oddworks/blob/master/lib/services/catalog/commands/index.js#L24

**Comment by brkattk** [comment]
This is no longer an issue as Pro and Business accounts give non-expiring URLs to video files
