### ISSUE TITLE
Handle API differences between PRO and free Vimeo accounts

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks-vimeo-provider#5]
API responses for `https://api.vimeo.com/me/videos/{videoId}` when using a free Vimeo account do not include the files, which requires us to make an addition call to a completely separate, undocumented API `https://player.vimeo.com/videos/{videoId}/config` that Vimeo uses for their player.

Luckily we were given access to a Pro account so I was able to notice that the second call is unnecessary in that case. I'm wondering if we should leave the second call in, or require a Pro account. It's likely that the second API could change without any notice, whereas I feel like `api.vimeo.com` would be stable enough for our uses.

@kixxauth just a heads up

**Comment by kixxauth** [comment]
Ok, thanks man.

So far, we've been expecting our customers to be vimeo pro users, so let's stick with that (and the documented API) 👍
